/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.Paneles;

import Clases.Pregunta;
import javax.swing.JButton;

/**
 *
 * @author Alejandro
 */
public class PanelPregunta extends javax.swing.JPanel{

    /**
     * Creates new form PanelPregunta
     */
    public int respuesta;
    public PanelPregunta(Pregunta p) {
        initComponents();
        labelPregunta.setText(p.getPregunta());
        radioRespuesta1.setText(p.getListRespuestas().get(0).getRespuesta());
        radioRespuesta2.setText(p.getListRespuestas().get(1).getRespuesta());
        radioRespuesta3.setText(p.getListRespuestas().get(2).getRespuesta());
        radioRespuesta4.setText(p.getListRespuestas().get(3).getRespuesta());
    }
    public PanelPregunta(Pregunta p, int posicion) {
        initComponents();
        selecionarRadio(posicion);
        labelPregunta.setText(p.getPregunta());
        radioRespuesta1.setText(p.getListRespuestas().get(0).getRespuesta());
        radioRespuesta2.setText(p.getListRespuestas().get(1).getRespuesta());
        radioRespuesta3.setText(p.getListRespuestas().get(2).getRespuesta());
        radioRespuesta4.setText(p.getListRespuestas().get(3).getRespuesta());
    }
    private void selecionarRadio(int posicion){
        switch(posicion){
            case 0:
                radioRespuesta1.setSelected(true);
                break;
            case 1:
                radioRespuesta2.setSelected(true);
                break;
            case 2:
                radioRespuesta3.setSelected(true);
                break;
            case 3:
                radioRespuesta4.setSelected(true);
                break;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoRespuestas = new javax.swing.ButtonGroup();
        labelPregunta = new javax.swing.JLabel();
        radioRespuesta1 = new javax.swing.JRadioButton();
        radioRespuesta2 = new javax.swing.JRadioButton();
        radioRespuesta3 = new javax.swing.JRadioButton();
        radioRespuesta4 = new javax.swing.JRadioButton();

        labelPregunta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPregunta.setText("¿Pregunta?");

        grupoRespuestas.add(radioRespuesta1);
        radioRespuesta1.setSelected(true);
        radioRespuesta1.setText("respuesta 1");
        radioRespuesta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRespuesta1ActionPerformed(evt);
            }
        });

        grupoRespuestas.add(radioRespuesta2);
        radioRespuesta2.setText("respuesta 2");
        radioRespuesta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRespuesta2ActionPerformed(evt);
            }
        });

        grupoRespuestas.add(radioRespuesta3);
        radioRespuesta3.setText("respuesta 3");
        radioRespuesta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRespuesta3ActionPerformed(evt);
            }
        });

        grupoRespuestas.add(radioRespuesta4);
        radioRespuesta4.setText("respuesta 4");
        radioRespuesta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRespuesta4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioRespuesta2, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                            .addComponent(radioRespuesta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radioRespuesta3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radioRespuesta4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(labelPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(labelPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioRespuesta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioRespuesta2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioRespuesta3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioRespuesta4)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {radioRespuesta1, radioRespuesta2, radioRespuesta3, radioRespuesta4});

    }// </editor-fold>//GEN-END:initComponents

    private void radioRespuesta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRespuesta1ActionPerformed
        respuesta = 0;
    }//GEN-LAST:event_radioRespuesta1ActionPerformed

    private void radioRespuesta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRespuesta2ActionPerformed
        respuesta = 1;
    }//GEN-LAST:event_radioRespuesta2ActionPerformed

    private void radioRespuesta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRespuesta3ActionPerformed
        respuesta = 2;
    }//GEN-LAST:event_radioRespuesta3ActionPerformed

    private void radioRespuesta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRespuesta4ActionPerformed
        respuesta = 3;
    }//GEN-LAST:event_radioRespuesta4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoRespuestas;
    private javax.swing.JLabel labelPregunta;
    private javax.swing.JRadioButton radioRespuesta1;
    private javax.swing.JRadioButton radioRespuesta2;
    private javax.swing.JRadioButton radioRespuesta3;
    private javax.swing.JRadioButton radioRespuesta4;
    // End of variables declaration//GEN-END:variables
}
